### PR TITLE
Change filenames to be accessible via require links

### PR DESCRIPTION
**Pull request by baerae-colin**
We can add KIP numbers to the required field in the specification.
The required KIPs are linked like kip-<number>, so the suffix of filenames
should be removed.

### CODE REVIEW

**Review by jimni1222 — APPROVED** [review]
LGTM :)

**Review by smseo — APPROVED** [review]
LGTM

**Review by aidan-kwon — APPROVED** [review]

**Comment by baerae-colin** [comment]
Sorry guys, I need to change links in the documentation. I will upload more commits, please approve this PR later. :)

**Comment by baerae-colin** [comment]
@smseo @KimKyungup @aidan-kwon @jimni1222 Updating link is done. The broken links are due to this filename change. Please take another look.

**Review by jimni1222 — APPROVED** [review]

**Review by KimKyungup — APPROVED** [review]

**Comment by aidan-kwon** [comment]
@kjhman21 Why don't you link to https://kips.klaytn.com/ ?
By the way, we better redirect HTTP URI to HTTPS URI on `kips.klaytn.com`.

**Comment by baerae-colin** [comment]
@aidan-kwon Thanks for letting me know. :) Updated.

**Pull request merged**
