### PR TITLE
[Proposal] KIP-13 Interface Query Standard

### PR DESCRIPTION
**Pull request by baerae-colin**
This PR proposes an interface query standard which is derived heavily from
ERC-165.

### CODE REVIEW

**Review by KimKyungup — APPROVED** [review]
This KIP has no differences with origin EIP-165.
Is it useful to make new KIP?

**Comment by baerae-colin** [comment]
@KimKyungup 
If we do not define "interface query standard", we always mention ERC-165 everytime we need that function in KIPs.

Do you think it is better to mention ERC-165 in KIPs?

**Review by joowon-byun — APPROVED** [review]

**Comment by KimKyungup** [comment]
> @KimKyungup
> If we do not define "interface query standard", we always mention ERC-165 everytime we need that function in KIPs.
> 
> Do you think it is better to mention ERC-165 in KIPs?

Well, I think If there is an exactly same ERC-XX with the KIP, I think it is ok to mention ERC-XX in KIPs. I'm curious about the opinions of others.
@jimni1222 @aidan-kwon @ehnuje @smseo @winnie-byun ?

**Review by jimni1222 — APPROVED** [review]
Both opinions make sense.
I think it depends on the direction Klaytn wants to go.

**Pull request merged**
